### ISSUE TITLE
Lbgpu does not compile with clang++ 4.0

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1239]
(on icp)
[ 19%] Building CXX object src/core/CMakeFiles/EspressoCore.dir/lb.cpp.o
/home/weeber/espresso-dev/src/core/lb.cpp:785:24: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'int' in initializer list [-Wc++11-narrowing]
            bb_high = {lbpar_gpu.dim_x-1, lbpar_gpu.dim_y-1, lbpar_gpu.dim_z-1};
                       ^~~~~~~~~~~~~~~~~
/home/weeber/espresso-dev/src/core/lb.cpp:785:24: note: insert an explicit cast to silence this issue
            bb_high = {lbpar_gpu.dim_x-1, lbpar_gpu.dim_y-1, lbpar_gpu.dim_z-1};
                       ^~~~~~~~~~~~~~~~~
                       static_cast<int>()
/home/weeber/espresso-dev/src/core/lb.cpp:785:43: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'int' in initializer list [-Wc++11-narrowing]
            bb_high = {lbpar_gpu.dim_x-1, lbpar_gpu.dim_y-1, lbpar_gpu.dim_z-1};
                                          ^~~~~~~~~~~~~~~~~
/home/weeber/espresso-dev/src/core/lb.cpp:785:43: note: insert an explicit cast to silence this issue
            bb_high = {lbpar_gpu.dim_x-1, lbpar_gpu.dim_y-1, lbpar_gpu.dim_z-1};
                                          ^~~~~~~~~~~~~~~~~
                                          static_cast<int>()
/home/weeber/espresso-dev/src/core/lb.cpp:785:62: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'int' in initializer list [-Wc++11-narrowing]
            bb_high = {lbpar_gpu.dim_x-1, lbpar_gpu.dim_y-1, lbpar_gpu.dim_z-1};
                                                             ^~~~~~~~~~~~~~~~~
/home/weeber/espresso-dev/src/core/lb.cpp:785:62: note: insert an explicit cast to silence this issue
            bb_high = {lbpar_gpu.dim_x-1, lbpar_gpu.dim_y-1, lbpar_gpu.dim_z-1};
                                                             ^~~~~~~~~~~~~~~~~
                                                             static_cast<int>()
3 errors generated.
