### ISSUE TITLE
Some test fails on OpenSuse 

### ISSUE THREAD

**Issue by junghans** [espressomd/espresso#2254]
From https://build.opensuse.org/request/show/634758
```
[  525s]   1/110 Test   #1: save_checkpoint .........................***Failed    3.00 sec
[  525s] Traceback (most recent call last):
[  525s]   File "/home/abuild/rpmbuild/BUILD/espresso-4.0.0/build/testsuite/save_checkpoint.py", line 39, in <module>
[  525s]     system.actors.add(lbf)
[  525s]   File "actors.pyx", line 186, in espressomd.actors.Actors.add
[  525s]   File "actors.pyx", line 48, in espressomd.actors.Actor._activate
[  525s]   File "lb.pyx", line 82, in espressomd.lb.LBFluid.validate_params
[  525s]   File "utils.pyx", line 334, in espressomd.utils.is_valid_type
[  525s] AttributeError: module 'numpy' has no attribute 'float128'
[  525s] -------------------------------------------------------
[  525s] Primary job  terminated normally, but 1 process returned
[  525s] a non-zero exit code.. Per user-direction, the job has been aborted.
[  525s] -------------------------------------------------------
[  525s] --------------------------------------------------------------------------
[  525s] mpiexec detected that one or more processes exited with non-zero status, thus causing
[  525s] the job to be terminated. The first process to do so was:
[  525s] 
[  525s]   Process name: [[1593,1],0]
[  525s]   Exit code:    1
[  525s] --------------------------------------------------------------------------
[  525s] 
```
Details [here](https://github.com/espressomd/espresso/files/2370996/log.txt)

**Comment by junghans** [comment]
@mkuron might be related to what you saw on OpenSuse 15

**Comment by mkuron** [comment]
This only happens on your 32-bit build. I think numpy just doesn't support 128-bit floats there. I have posted a patch.

Thanks for reporting all these issues. I saw that your builds for the exotic architectures (ppc64, ppc64le, s390x) are still failing. Please keep on reporting bugs and we'll try to fix them. Also, your SLE12 and openSUSE 42.3 builds should probably require _openmpi_ instead of _openmpi2_ to be resolvable.

**Comment by junghans** [comment]
Once the initial rpm request went in, you can take it over an and fix all the builds ;-)

**Comment by junghans** [comment]
Oh and it seems strange, that the i686 on Fedora doesn’t have that problem!

**Comment by junghans** [comment]
[opensuse_log.txt](https://github.com/espressomd/espresso/files/2372820/opensuse_log.txt)
There is something else wrong on openSUSE 42.3

**Comment by mkuron** [comment]
```
error: no matching function for call to 'boost::mpi::environment::environment()'
    mpi::environment mpi_env;
```
That comes from here:

https://github.com/boostorg/mpi/blob/e5fe21df2f42dda0ce8674a935d44e99739c4a19/include/boost/mpi/environment.hpp#L87-L101

https://github.com/boostorg/mpi/blob/56c2a212e5d9c43dab7ae873a0a8c2c7897327bd/include/boost/mpi/config.hpp#L37-L57

`MPI_VERSION` is unconditionally set to `3` in _mpi.h_, so it seems like the MPI headers are broken in your build container. It works fine in our Docker images and on our 42.3 machines. I have added a patch to #2255 though as it's inconsistent that this is the only test where we don't pass `argc, argv` to `boost::mpi::environment`.

**Comment by junghans** [comment]
It is not _my_ build container, but the one OpenSUSE Build Service is using ;-)

**Comment by mkuron** [comment]
I know. I actually found the cause of the problem though: in Boost 1.54, it explicitly checks for `MPI_VERSION == 2`, which was not fixed until Boost 1.56. Can you apply #2255 and see if that fixes it?

**Comment by junghans** [comment]
I am playing around with it here: https://build.opensuse.org/package/show/home:cjunghans:branches:devel:languages:python/python-espressomd

**Comment by junghans** [comment]
Leap 15.0 and 42.3 and Tumbleweed seems to be ok now with #2255. I will post the build issues on ppc64le in a bit!
