### ISSUE TITLE
CUDA code does not build on ubuntu

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#829]
On ubuntu xenial the CUDA code does not build with the packaged nvcc.

```
[  1%] Building NVCC (Device) object src/core/CMakeFiles/EspressoCuda.dir/EspressoCuda_generated_cuda_common_cuda.cu.o
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00000b1d_00000000-13_cuda_common_cuda.compute_50.cpp1.ii".
CMake Error at EspressoCuda_generated_cuda_common_cuda.cu.o.cmake:262 (message):
  Error generating file
  /home/florian/Source/espresso/build/src/core/CMakeFiles/EspressoCuda.dir//./EspressoCuda_generated_cuda_common_cuda.cu.o


src/core/CMakeFiles/EspressoCuda.dir/build.make:387: recipe for target 'src/core/CMakeFiles/EspressoCuda.dir/EspressoCuda_generated_cuda_common_cuda.cu.o' failed
make[2]: *** [src/core/CMakeFiles/EspressoCuda.dir/EspressoCuda_generated_cuda_common_cuda.cu.o] Error 1
CMakeFiles/Makefile2:1502: recipe for target 'src/core/CMakeFiles/EspressoCuda.dir/all' failed
make[1]: *** [src/core/CMakeFiles/EspressoCuda.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

The version in the packages is
```
Cuda compilation tools, release 7.5, V7.5.17
```

**Comment by fweik** [comment]
This has come up before, but I don't think there is a ticket....

**Comment by rbardak** [comment]
I think this is a xenial specific problem. I've seen solutions which force
strict ansi rules, however I can't seem to find them.
I also seem to remember reading something that nvcc doesn't like being
linked against libraries built by the current version of gcc available on
xenial. However I didn't test any of these ideas.

**Comment by mkuron** [comment]
CUDA 7.5 only works with GCC 4.9.x and lower. Please download the CUDA 8 beta. The issue cannot be fixed from our side.

**Comment by psci2195** [comment]
Yes, I've also investigated this issue. I've tried different hacks with not so much success (like [https://www.pugetsystems.com/labs/hpc/NVIDIA-CUDA-with-Ubuntu-16-04-beta-on-a-laptop-if-you-just-cannot-wait-775/](url)). Anyway, all options were unofficial and not supported. This is a reason why I finally disabled my Ubuntu upgrade and keep using of ```Ubuntu 14.04.5 LTS```with Espresso until Nvidia CUDA will officially support latest stable Ubuntu.
